- hosts: kubs
  become: yes
  tasks:
  - name: Install needed packages
    command: yum install -y yum-utils device-mapper-persistent-data lvm2

  - name: install repo
    command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    
  - name: Install docker
    package:
      name: docker
      state: installed

  #- name: add user to docker group
  #  command: usermod -aG docker $(whoami)

  - name: start docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: install docker compose repo
    command: yum install epel-release -y

  - name: install python-pip
    command: yum install -y python-pip

  - name: install docker compose
    command: pip install docker-compose
  
 
