- hosts: 192.168.0.22
  become: yes
  tasks:
    - name: Install java
      package:
        name: java-1.8.0-openjdk-devel
        state: installed
    
    - name: Install wget
      package:
        name: wget 
       
    - name: enable jenkins repo
      command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    
    - name: add repo
      command: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key 

    - name: Install jenkins
      command: yum install jenkins -y

    - name: enable jenkins
      command: systemctl enable jenkins

    - name: start jenkins
      command: systemctl start jenkins

    - name: setup firewall
      command: firewall-cmd --permanent --zone=public --add-port=8080/tcp

    - name: reload firewall
      command: firewall-cmd --reload
